version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/twilio-video-diagnostics-react-app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run: npm ci

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

      - run:
          name: 'Jest Unit Tests'
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'test-reports/jest'
            JEST_JUNIT_OUTPUT_NAME: 'results.xml'
            JEST_JUNIT_CLASSNAME: '{classname}'
            JEST_JUNIT_TITLE: '{title}'

      - store_artifacts:
          path: coverage

      - store_test_results:
          path: test-reports

      - run:
          name: 'Eslint'
          command: npm run lint -- --max-warnings 0

      - run:
          name: 'Build App'
          command: npm run build

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
